### ISSUE TITLE
FSP Checklist

### ISSUE THREAD

**Issue by Carly-Schaaf** [dropspindl/MyInterest#1]
# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - [x] Includes the following list for the 4 app specific MVPs:
    - [x] Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
- [x] Add details for each MVP to describe the feature in more detail – you can use "user stories" such as "Users cannot sign up with the same username/password", "Users are redirected to the home-page on sign up", etc.

# DB Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
- [x] If `firstname` and `username` are separate data, you should include both in your table
- [ ] add an index to whichever column you use for authentication (probably `username`) for faster lookup
- [x] `creator` should be `creator_id` 
- [x] You won't need `image_url` anywhere on the backend (we'll use active storage)
- [x] pins table should also have a `creator_id`
- [x] How will pins be associated to boards? You probably need to add a `PinBoard` joins table

# API Routes
- [x] You'll still want to fetch individual user info by their `id` (RESTful convention), so the show route will still be `/api/users/:user_id`. On the frontend, it's fine if you want to have your route be `/users/:userId` as well. 
- [x] For board routes, you can create nested routes, like: `/api/users/:user_id/boards`, but it might be easier to just make normal restful routes (`/api/boards`) and pass the `user_id` as a param in your request. Either way, you should re-write these to be RESTful:

```rb
GET /api/boards
POST api/boards
GET api/:boards/:board_id
PATCH api/:boards/:board_id
DELETE api/:boards/:board_id

GET /api/pins/:pin_id
POST /api/pins
PATCH /api/pins/:pin_id
DELETE /api/pins/:pin_id 
```
# Frontend Routes
- [x] You're going to make it, don't worry!

# Sample State
- [x] Looks great except you'll need to have some way of storing the relationship between pins and boards (possibly a joins table?)

**Comment by Carly-Schaaf** [comment]
You're off to a good start, Erica! Be sure to finish this up tomorrow after the assessment. As soon as the Frontend Routes are made and the unchecked boxes are completed, you're good to go! Feel free to ask me any questions along the way

**Comment by dropspindl** [comment]
The checklist is finished! Do I check the unchecked items off or do you?

**Comment by Carly-Schaaf** [comment]
Awesome! I'll check them off as I look it over :)

**Comment by Carly-Schaaf** [comment]
Looks great, Erica! Just a few things:

- [ ] your follow-board feature should be one of your main MVPs, and follow-users should be bonus
- [ ] add an index to `username`
- Regarding your question "Do joins tables get routes??", you don't need a route for your joins table because you can use your model-level association. For example, if you want all the pins for a specific board on your board show page, you can just call @board.pins in order to get those pins.
